const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { PluginLoader } = require('../lib/plugin-loader')
const { PluginHost } = require('../lib/plugin-host')

test('editable source packages reload imported modules and styles, and retain working code on errors', async t => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'source-plugin-'))
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }))
  const folder = path.join(directory, 'notes')
  fs.mkdirSync(folder)
  const manifest = { sisyphus: { id: 'feature.notes', entry: './view.ts', export: 'plugin',
    native: [{ id: 'desktop.notes', entry: './native.cjs' }] } }
  fs.writeFileSync(path.join(folder, 'package.json'), JSON.stringify(manifest))
  fs.writeFileSync(path.join(folder, 'view.ts'), "import './style.css'; export const plugin = { apply() {} }")
  fs.writeFileSync(path.join(folder, 'style.css'), 'button { color: blue; }')
  fs.writeFileSync(path.join(folder, 'native.cjs'), "const value = require('./value.cjs'); module.exports = () => ({ provide: ['notes'], apply(ctx) { ctx.provide('notes', value) } })")
  fs.writeFileSync(path.join(folder, 'value.cjs'), 'module.exports = 1')
  const { Profile } = await import('@sisyphus/profile')
  const runtime = new Profile()
  const loader = new PluginLoader(directory)
  const host = new PluginHost({ loader, runtime, watching: false })
  t.after(async () => { await host.close(); await runtime.dispose() })
  await host.sync()
  assert.equal(runtime.get('notes'), 1)
  assert.match(loader.read('feature.notes', 'renderer').source, /export const plugin/)
  assert.match(loader.render('feature.notes').source, /SisyphusRuntime.register/)
  assert.match(loader.render('feature.notes').css, /blue/)

  fs.writeFileSync(path.join(folder, 'value.cjs'), 'module.exports = 200')
  fs.writeFileSync(path.join(folder, 'style.css'), 'button { color: red; }')
  await host.reload()
  assert.equal(runtime.get('notes'), 200, 'local imports are re-evaluated')
  assert.match(loader.render('feature.notes').css, /red/)

  fs.writeFileSync(path.join(folder, 'value.cjs'), 'module.exports = ;')
  await host.reload('desktop.notes')
  assert.equal(runtime.get('notes'), 200)
  assert.match(host.catalog().plugins.find(entry => entry.id === 'desktop.notes').error, /Build failed/)
  fs.writeFileSync(path.join(folder, 'package.json'), '{ half saved')
  await host.sync()
  assert.equal(runtime.get('notes'), 200, 'an invalid manifest must not unmount the working package')
})

test('Cordis restores the previous plugin when replacement fails during apply', async () => {
  const { Profile } = await import('@sisyphus/profile')
  const runtime = new Profile()
  const plugin = { provide: ['answer'], apply(ctx) { ctx.provide('answer', 42) } }
  await runtime.add({ id: 'answer', plugin })
  await assert.rejects(runtime.replace('answer', { apply() { throw new Error('bad edit') } }), /bad edit/)
  assert.equal(runtime.get('answer'), 42)
  await runtime.dispose()
})
